### ISSUE TITLE
NoFOG mod catching errors, maybe due to spaces in minecraft:worldgen/biome / underground_jungle:underground_jungle

### ISSUE THREAD

**Issue by esvarc** [HexagonNico/UndergroundJungle#3]
game Version 1.20.1
forge Version 1.20.1-47.2.0
NoFog version nofog-1.3.4_1.20.1-forge
Underground Jungle version undergroundjungle-2.0.2-forge-1.20.1.jar

error 

```
[10:57:37] [modloading-worker-0/ERROR] [no_fog/CATCHING]: Catching
java.lang.IllegalStateException: Errors during registry creation
	at net.minecraft.core.RegistrySetBuilder$BuildState.m_255178_(RegistrySetBuilder.java:136) ~[client-1.20.1-20230612.114412-srg.jar%23358!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.core.RegistrySetBuilder.m_255144_(RegistrySetBuilder.java:62) ~[client-1.20.1-20230612.114412-srg.jar%23358!/:?] {re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
	at net.minecraft.data.registries.VanillaRegistries.m_255371_(VanillaRegistries.java:72) ~[client-1.20.1-20230612.114412-srg.jar%23358!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:worldgenrevisited.mixin.json:VanillaRegistriesAccessor,pl:mixin:A}
	at virtuoel.no_fog.util.ConfigUtils.populateDimensionToggles(ConfigUtils.java:54) ~[v201-nofog-1.3.4_1.20.1-forge.jar%23321!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at virtuoel.no_fog.util.DummyNoFogConfig.<init>(DummyNoFogConfig.java:11) ~[v201-nofog-1.3.4_1.20.1-forge.jar%23321!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at virtuoel.no_fog.NoFogClient.<clinit>(NoFogClient.java:28) ~[v201-nofog-1.3.4_1.20.1-forge.jar%23321!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.2.1.jar%23360!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.2.1.jar%23359!/:?] {re:mixin}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames,pl:rei_plugin_compatibilities:B}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames,pl:rei_plugin_compatibilities:B}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / underground_jungle:underground_jungle]
		at net.minecraft.core.RegistrySetBuilder$BuildState.m_255228_(RegistrySetBuilder.java:126) ~[client-1.20.1-20230612.114412-srg.jar%23358!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
		at net.minecraft.core.RegistrySetBuilder.m_255144_(RegistrySetBuilder.java:61) ~[client-1.20.1-20230612.114412-srg.jar%23358!/:?] {re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
		at net.minecraft.data.registries.VanillaRegistries.m_255371_(VanillaRegistries.java:72) ~[client-1.20.1-20230612.114412-srg.jar%23358!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:worldgenrevisited.mixin.json:VanillaRegistriesAccessor,pl:mixin:A}
		at virtuoel.no_fog.util.ConfigUtils.populateDimensionToggles(ConfigUtils.java:54) ~[v201-nofog-1.3.4_1.20.1-forge.jar%23321!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
		at virtuoel.no_fog.util.DummyNoFogConfig.<init>(DummyNoFogConfig.java:11) ~[v201-nofog-1.3.4_1.20.1-forge.jar%23321!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
		at virtuoel.no_fog.NoFogClient.<clinit>(NoFogClient.java:28) ~[v201-nofog-1.3.4_1.20.1-forge.jar%23321!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.2.1.jar%23360!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.2.1.jar%23359!/:?] {re:mixin}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames,pl:rei_plugin_compatibilities:B}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames,pl:rei_plugin_compatibilities:B}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}

```

**Comment by HexagonNico** [comment]
There are no spaces in `underground_jungle/worldgen/biome/underground_jungle.json`, so I don't think that's the problem. I'm not sure what the error is though, because it's being thrown by another mod.

**Comment by esvarc** [comment]
Thanks for clarifying that there is no space in the biome name. So far, I have not come across that the described error in the log has an effect on the existence of the sub-zone biome and the placement of structures in it. In this case, it looks like the NoFog mod has a problem registering the new biome underground. Surely I have to deal with the given error with the author of the NoFog mod. And thanks for your work.

**Comment by esvarc** [comment]
👍
